### ISSUE TITLE
OpenCL does not work for standard conda installation of bempp-cl

### ISSUE THREAD

**Issue by pimanov-h** [bempp/bempp-cl#104]
Hi everybody,

I stuck with a problem on standard conda installation of bempp-cl. In my case, opencl does not work. 

At first, I installed the newest version of anaconda from https://www.anaconda.com/products/individual.
Then I installed bempp-cl=0.2.2 into a new conda environment by the command:
```
conda create -n bempp-cl-env -c conda-forge bempp-cl=0.2.2 notebook matplotlib
```

If I set `bempp.api.DEFAULT_DEVICE_INTERFACE = 'numba'` everything works.
If `bempp.api.DEFAULT_DEVICE_INTERFACE = 'opencl'` (by default) Jupyter kernel appears to have died when I try to assemble the matrix (solve the system). In particular, it is the case for any of tutorials on bempp.com. When I run the same code in python script I can see that it is segmentation fault. 

Command `bempp.core.opencl_kernels.show_available_platforms_and_devices()` returns
```
0: Portable Computing Language
    0: pthread-Intel(R) Xeon(R) Gold 6144 CPU @ 3.50GHz
```
so bempp-cl can see only CPU and no GPUs. 

Command  `print(bempp.core.opencl_kernels.default_device())` returns
```
<pyopencl.Device 'pthread-Intel(R) Xeon(R) Gold 6144 CPU @ 3.50GHz' on 'Portable Computing Language' at 0x562e2a1c1830>
```
so default_device is the CPU. 

Few months ago, it was no problems with bempp-cl installed in the same way on the same machine. The operation system is CentOS 8. The machine has 32 Intel processors and GPU NVIDIA Tesla V100. 

Have you any idea how to fix this?

**Comment by tbetcke** [comment]
I had a similar problem recently with Fedora 33. Maybe, it is related. In conda I had to downgrade to POCL Version 1.5 build hecece54_4. Interestingly, this seems not to be an issue on Ubuntu 20.04.

**Comment by pimanov-h** [comment]
Thank you! Downgrading POCL version from 1.6 to 1.5 fixed the problem. Maybe it makes sense to put a restriction on pocl = 1.6 in the conda package?

**Comment by tbetcke** [comment]
We have to investigate this further. I haven't seen this issue on Ubuntu (but need to check more). I am also not sure if it is really POCL related as later builds of POCL 1.5 on Conda do create the issue. The only change is different dependencies in Conda. I will need to bump this up to the POCL developers. But closing this bug report for now as not in Bempp-cl.

**Comment by SDSearch** [comment]
Hello Everyone,

I have just run into this problem on a workstation running Ubuntu 18.04.4 LTS. As suggested above, downgrading POCL from version 1.6 to 1.5 fixed the problem.

**Comment by pimanovvlad** [comment]
Hi!
The same issue on Linux Mint 17.3 Rosa.
Downgrading POCL from version 1.6 to 1.5 fixed the problem.
