### ISSUE TITLE
Numba error in clean install of bempp

### ISSUE THREAD

**Issue by philmain28** [bempp/bempp-cl#115]
I am getting an error with numba (due to an update maybe?) .  Installing to a clean conda environment and running the first cell of notebook:
/bempp-cl/notebooks/laplace/dirichlet_weak_imposition.ipynb

I get the following traceback:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-7901a1c4971a> in <module>
----> 1 import bempp.api
      2 import numpy as np

~/.local/lib/python3.9/site-packages/bempp/api/__init__.py in <module>
      7 
      8 import pyopencl as _cl
----> 9 from bempp.api.utils import DefaultParameters
     10 from bempp.api.utils.helpers import MemProfiler
     11 

~/.local/lib/python3.9/site-packages/bempp/api/utils/__init__.py in <module>
      3 from .which import which
      4 from .parameters import DefaultParameters
----> 5 from .octree import Octree
      6 

~/.local/lib/python3.9/site-packages/bempp/api/utils/octree.py in <module>
      5 
      6 
----> 7 @_numba.jitclass(
      8     [
      9         ("_lbound", _numba.float64[:]),

AttributeError: module 'numba' has no attribute 'jitclass'

**Comment by yu-ting-py** [comment]
Hi

I got the same problem while installation.

It seems that numba update this part, and `jitclass` is no longer supported.

https://numba.pydata.org/numba-doc/latest/user/jitclass.html

**Comment by philmain28** [comment]
I managed to get it working by preinstalling numba == 0.48.0.

**Comment by yu-ting-py** [comment]
Hi

But I got conflict:

` - bempp-cl -> numba[version='>=0.51.2']`

how do you install an early version?

**Comment by philmain28** [comment]
I just reinstalled from scratch.

**Comment by tbetcke** [comment]
Hi. Thanks for the comments. It looks like `jitclass` has been moved to a different location. I will prepare a new bugfix release after the weekend. There are a couple of other bugfixes that should be released as well.

**Comment by tbetcke** [comment]
Fixed in Master
