### ISSUE TITLE
installation : GMSH not found

### ISSUE THREAD

**Issue by antoineRallu** [bempp/bempp-cl#130]
Hi,
I'm on windows 10 and working with python 3.8.3 on Spyder 5.1.5.

I've followed the instructions for installing bempp-cl, and I checked that GMSH works. However, "Solving your first problem with Bempp" doesn't work for me because "Gmsh is not found. Cannot generate mesh". 

When I look in the __init__ file of bempp, I see the the variable GMSH_PATH is defined (not NONE) if the file "gmsh.exe" (because _os="nt" on windows) is found in the scripts directory. However in this directory there is two files : "gmsh.bat" and "gmsh" without extension.

How to force bempp to see gmsh? I've tried to modify the __init__ code, (removing .exe) line 222 but other errors appear after.

**Comment by Railon69** [comment]
Hey :)
I got the same problem with the "RuntimeError: Gmsh is not found. Cannot generate mesh".
I installed both, python installation and gmsh windows native installation. The problem with the windows installation is that it is just a zip file which is extracted and does not have a /bin directory. Also adding the .exe file into Window's system path does not work. How did you do it exactly?

I used the windows zip file from "https://www.gmsh.info/"

Thank you really much!
