### ISSUE TITLE
plotly and paraview missing from Numba-only Docker image

### ISSUE THREAD

**Issue by DAWardle** [bempp/bempp-cl#139]
Hi Bempp.

I'm using the Numba-only Docker image on a Windows computer.

If I try and reproduce [Solving your first problem with Bempp](http://bempp.com/documentation/get_started.html), I don't get the pretty picture (I think because neither plotly nor paraview are included in the Docker image?).

This is not a problem for me at all.  And I appreciate that, the more features included in the Docker image, the larger the Docker image becomes to download and install.  But I thought I'd point it out as it might dishearten beginners.

Yours sincerely,

David Wardle.

**Comment by mscroggs** [comment]
I'll take a look at adding the plotting libraries to the docker image. As the image is designed to primarily run Jupyter Lab, I think it makes most sense to include plotly but maybe not paraview.

(I'll also check they're included in the images with OpenCL as I may have missed them there too.)
