### ISSUE TITLE
Could not find Gmsh.Interactive plotting and shapes module not available.

### ISSUE THREAD

**Issue by my1e5** [bempp/bempp-cl#163]
I have installed `bempp-cl 0.2.4` and I have `gmsh 4.6.0` installed as well. But when I try:

```
$ python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bempp.api
Could not find Gmsh.Interactive plotting and shapes module not available.
```

`gmsh` is in the system path.

**Comment by evantwout** [comment]
This issue seems to be related to the following discussion on Discourse: https://bempp.discourse.group/t/fail-to-import-the-package-bempp-api/127. Please consider those suggestions and check if they work.
