### ISSUE TITLE
has the api changed?

### ISSUE THREAD

**Issue by de-gozaru** [bempp/bempp-cl#170]
Hi,

I'm using python 3.8.

I just installed `bempp` using pip:
```
pip3 install bempp-cl
```
and I'm trying to run a code I found on github, but I'm getting some basic error, that I think are due to change of api. Some of the errors are:
```python
import bempp.api

bempp.api.boundary_operator_assembly_type = "hmat"
bempp.api.potential_operator_assembly_type = "hmat"

bempp.api.global_parameters.hmat.eps = eps
```
gives
```bash
AttributeError: module 'bempp.api' has no attribute 'global_parameters'
```
and the line:
```python
grid = bempp.api.grid_from_element_data(vertices, elements)
```
gives
```bash
AttributeError: module 'bempp.api' has no attribute 'grid_from_element_data'
```

Are these errors due to a change of api, if so, which version should I use to make them work?

Thank you in advance!

**Comment by evantwout** [comment]
The version you installed with pip is the current bempp-cl library. The code you are trying to run is for the legacy bempp library, version 3. The new bempp-cl library is not backward compatible with bempp v3.

**Comment by de-gozaru** [comment]
Hi @evantwout 

Thank you for answer!
So, is there a way to 'translate' the lagacy code to the new version of the library, if so, can you give me a hint on how to do so?

Thank you in advance!

**Comment by evantwout** [comment]
There is no direct translation between versions. Many functions have the same syntax, but others are different. You need to read the documentation and the tutorials to see the differences.

In this specific case: bempp-cl does not have H-matrix compression anymore but provides an interface to the ExaFMM library for fast matrix arithmetic.

**Comment by de-gozaru** [comment]
Hi @evantwout 

I see, thank you for your answer!

Is there a way to install the legacy bempp library for python3, so I can first, test the code I found on github, and if it does the job to me, spend the extra time adapting it to the new version?

Thank you in advance!

**Comment by evantwout** [comment]
You can find the installation instructions of the legacy bempp v3 on the official website: https://bempp.com/bempp334/installation.html

**Comment by mscroggs** [comment]
closing this as it appears to be resolved. Feel free to reopen it if I've misunderstood
