### ISSUE TITLE
PyPI page does not seem to be in English

### ISSUE THREAD

**Issue by nicoguaro** [bempp/bempp-cl#176]
I was trying to check the dependencies in the pip version of the package and found the following:

![image](https://user-images.githubusercontent.com/1097787/198329104-8e27cbd6-0d68-484e-90fd-8e199e727f65.png)

**Comment by mscroggs** [comment]
It appears to be in English for me. Can you go to https://pypi.org/project/Bempp-cl/ and check if this is still an issue?

**Comment by nicoguaro** [comment]
It does appear in English now for me.
