### ISSUE TITLE
The problem of FEM-BEM coupling when using fenics-dolfinx [v0.6.0]

### ISSUE THREAD

**Issue by fegshen** [bempp/bempp-cl#184]
I installed fenics-dolfinx [v0.6.0] from source and tried to run the bempp-cl test code. Is there a bug in bempp/api/external/fenicsx.py  in [line19]?
![image](https://user-images.githubusercontent.com/32871840/222736040-79991bc1-2d27-4371-8565-6decd6036194.png)

And If I modified the source code in bempp/api/external/fenicsx.py in [lines 18-23] as:
```
boundary = entities_to_geometry(
        fenics_mesh,
        fenics_mesh.topology.dim - 1,
        exterior_facet_indices(fenics_mesh.topology),
        True,
    )
```
then everything is PASSED.

**Comment by mscroggs** [comment]
I added that `.cpp_object` recently to reflect a change in FEniCSx, but maybe that change happened since v0.6.0. I'll check and probably revert it until the next FEniCSx release

**Comment by mscroggs** [comment]
I've added a try...except so that the coupling can work with older and newer versions of FEniCSx. Let me know if it still doesn't work
