### ISSUE TITLE
[enhancement] In case of pip install with the new scipy

### ISSUE THREAD

**Issue by Insoka** [bempp/bempp-cl#210]
It is just a suggestion, I'm aware that the conda install avoid this problem but I like to install the package with pip.

In case of pip installation of bempp, if you have the recent version of scipy and test the example (https://bempp.com/documentation/get_started.html). It will not work. In order to work I made change in the file iterative_solvers.py (line 205 and others lines need to be change but is not related with the example) for the new tolerance definition. After the example work as intended (same results) but I do not know what tol in the function scipy.sparse.linalg.gmres in the old function. It would also require the modification of all occurrences of this function in the library for running with pip with the new scipy library.

**Comment by artpelling** [comment]
Facing the same problem. It would be nice to have proper dependency definitions to allow for easy installation with `pip`. I had to manually install `numba`, `meshio` and `gmsh` and downgrade `scipy` in order for it to work.

**Comment by Insoka** [comment]
Thank for your answers, I'll do as you say. With my virtualenv, I have the following numba==0.60.0
meshio==5.3.5
gmsh==4.13.1
numpy=2.0.1
and with the changes mentioned above. It works without need to compiling anything (the list may be non-exhaustive). I prefer to use pip because it's easier for me to mix libraries. I know how to use Conda but the project is less free and it seems more complicated for me to mix different libraries together (probably I don't have enough experience).

**Comment by ymei** [comment]
Looking at the code, the default value `tol=1e-5` appears to be the default for `rtol` in `scipy.sparse.linalg.gmres`.  So I simply changed `tol` to `rtol`, and the results appear to be the same.  Is this a fix?

**Comment by mscroggs** [comment]
I think this is fixed in the 0.3.2 release. Please reopen this if not!
