### ISSUE TITLE
/assembly/discrete_boundary_operator.py uses deprecated _np.promote_types which fails on numpy>=2.0.2

### ISSUE THREAD

**Issue by joverbee** [bempp/bempp-cl#213]
fresh install on mac m3 caused some exception

change to use _np.promote_types() seems to solve it

line 77 dtype = _np.promote_types(op1.dtype, type(alpha))
line 108 dtype = _np.promote_types(op1.dtype, op2.dtype)
line 138 dtype = _np.promote_types(op1.dtype, op2.dtype)

**Comment by mscroggs** [comment]
I think this is fixed in the 0.3.2 release. Please reopen this if not!
