### ISSUE TITLE
Use pygmsh to make built-in grids

### ISSUE THREAD

**Issue by mscroggs** [bempp/bempp-cl#25]
Using pygmsh would be neater than using `os.system("gmsh file.geo")` and will be less likely to have issues on (eg) Windows

**Comment by tbetcke** [comment]
Does pygmsh work in Windows? Our current method is clunky but works in Windows.

**Comment by mscroggs** [comment]
I will check before doing anything about this

**Comment by mscroggs** [comment]
We've decided not to do this
