### ISSUE TITLE
pip install doesn't pull in deps

### ISSUE THREAD

**Issue by cbm755** [bempp/bempp-cl#3]
Python modules I needed to install:
  * numba
  * pyopencl
  * meshio

Also, until I got `gmsh` I got this message:
```
>>> import bempp.api                                                        
Could not find Gmsh.Interactive plotting and shapes module not available.
```
But its not clear (yet, to me) if this is a critical failure.

**Comment by cbm755** [comment]
In fact, I needed the "gmsh" binary, not just the python module.  On Fedora I did:
```
dnf install python3-gmsh
dnf install gmsh
```
The former was not sufficient: I got:
```
RuntimeError: Gmsh is not found. Cannot generate mesh
```

**Comment by tbetcke** [comment]
Gmsh is not a mandatory dependency for the functionality of the software. However, we may add the dependency in the next version as it effects some non-core functionality.

**Comment by cbm755** [comment]
@tbetcke but shouldn't the other dependencies be specified on pypi?

**Comment by nkatteface** [comment]
I am still having issue with "Could not find Gmsh. Interactive plotting and shapes module not available"Any help will be appreciated.
Kind regards

**Comment by tbetcke** [comment]
Gmsh needs to be in your system path to be found. If you are on Linux you can install Gmsh through conda or through your Package manager. Please note that the version on PyPi is outdated. We had some accoutnt issiues that prevented updating. On conda gmsh is automatically installed as dependency if you install Bempp-cl 0.2.2

**Comment by nkatteface** [comment]
Thank you !!!The first time ( July-September 2020) I installed anaconda with python 3.8 on my computer, the bempp library worked perfectly.  At this this time I had problems running another software on my machine. Then I deleted every python programs, and reinstalled  it, for some reason this Gmsh is not working.
Kind regards,Nkorni Katte



    On Friday, March 19, 2021, 06:07:52 AM EDT, tbetcke ***@***.***> wrote:  
 
 


Gmsh needs to be in your system path to be found. If you are on Linux you can install Gmsh through conda or through your Package manager. Please note that the version on PyPi is outdated. We had some accoutnt issiues that prevented updating. On conda gmsh is automatically installed as dependency if you install Bempp-cl 0.2.2
