### ISSUE TITLE
global dirichlet space: Requested space not implemented.

### ISSUE THREAD

**Issue by cbm755** [bempp/bempp-cl#5]
Still following [1], I got:
```py
>>> global_dirichlet_space = bempp.api.function_space(grid, "P", 2)

ValueError: Requested space not implemented.
```
It succeeds if I pass `1` instead of `2`.

[1] https://nbviewer.jupyter.org/urls/bitbucket.org/bemppsolutions/bempp-tutorials/raw/master/notebooks/mixed_neumann_dirichlet.ipynb

**Comment by tbetcke** [comment]
Bempp-cl only supports constant and linear spaces at the moment. See an adapted tutorial at https://github.com/bempp/bempp-cl/blob/master/notebooks/laplace/mixed_neumann_dirichlet.ipynb
