### ISSUE TITLE
error when using opencl on a Radeon5600XT

### ISSUE THREAD

**Issue by arieder** [bempp/bempp-cl#63]
Hello,

I tried using the new bempp-cl on my computer (FMM and opencl) and get lots of error messages of the form 
"error: unknown type name 'REALTYPEVEC'
__kernel __attribute__((vec_type_hint(REALTYPEVEC))) void kernel_function"

I think it might be because my graphics card reports "Preferred / native vector sizes" as "1/1" for float and double in clinfo.

Adding something like #define REALTYPEVEC REALTYPE to bempp/core/sources/include/bempp_base_types.h the error seems to go away. 

best,
Alex

**Comment by tbetcke** [comment]
Thank you for the error message. This issue should appear when you set

`bempp.api.VECTORIZATION_MODE = "novec"
`
Could you try this?

**Comment by arieder** [comment]
it doesn't appear to make a difference

**Comment by tbetcke** [comment]
Which operator are you trying? It should automatically use a GPU optimised kernel without vectorized data types with this global option.

**Comment by arieder** [comment]
the problematic assembly  is

sl=bempp.api.operators.boundary.laplace.single_layer(bem_dc,bem_c,bem_dc,assembler="fmm", device_interface="opencl")

**Comment by tbetcke** [comment]
Thanks. I can confirm the bug now. This slipped through. Unfortunately, we do not have a good automatic testing infrastructure for GPUs. I will fix it for the next patch release.

**Comment by tbetcke** [comment]
Bempp-cl v0.2.2 has just been published that fixes this issue.
