### ISSUE TITLE
Incorrect data in local2global

### ISSUE THREAD

**Issue by mscroggs** [bempp/bempp-cl#72]
When cells have fewer DOFs than they might (eg cells on the boundary for RWG space on a screen), the values in local2global that should be None or -1 (as there is no DOF for that local index) are currently given values.

This causes this test that I've just added to fail:
https://github.com/bempp/bempp-cl/blob/3a1d9abbdd27e7d9275811459e7544f0a37b4f43/test/unit/space/test_space.py#L268-L300

**Comment by mscroggs** [comment]
Actually, I think this is intended. In each of these cases, the `local_multiplier` is 0 so it doesn't matter which DOF number is placed at the point

**Comment by tbetcke** [comment]
Exactly. I implemented it in this way as in the old Bempp whenever we iterated through local multipliers we had to check for the -1 case. Now all these conditional iterations are not necessary any more.
