### ISSUE TITLE
Suggested amendment to `Example application' `Bistatic RCS generated by dielectric spheres' 

### ISSUE THREAD

**Issue by DAWardle** [bempp/bempp-cl#92]
Hi Bempp.

I wish to solve a simple scattering problem.  I'm trying to adapt the `Example application` `Bistatic RCS generated by dielectric spheres`:
https://nbviewer.jupyter.org/github/bempp/bempp-cl/blob/master/notebooks/maxwell/maxwell_dielectric.ipynb

One thing I would find really helpful would be to have one of the spheres in the example to be made of teflon (a lossless dielectric with real permittivity) and one made of e.g. water (a lossy dielectric with complex permittivity), rather than both spheres being teflon (as is currently the case).  The `Example application' would then be even more useful as it would show how to deal, not only with any number of objects, but also with objects made of any dielectric material.

This is not a bug or a criticism --- just a suggestion for improvement.

**Comment by tbetcke** [comment]
Apologies for the late response. Noted. It is actually very easy to adapt the code to the situation. We may do it in a future release.
